# Generated by Django 3.0.7 on 2020-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlides',
            fields=[
                ('slide_id', models.AutoField(primary_key=True, serialize=False)),
                ('slide_heading', models.CharField(max_length=100)),
                ('slide_desc', models.CharField(max_length=500)),
                ('slide_img', models.ImageField(upload_to='Evento/images')),
            ],
        ),
    ]
