# Generated by Django 3.0.7 on 2020-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_auto_20200706_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_heading', models.CharField(max_length=100)),
                ('F_desc', models.CharField(max_length=500)),
                ('F_img', models.ImageField(upload_to='Evento/images')),
            ],
        ),
    ]
