# Generated by Django 3.0.7 on 2020-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold_Plan',
            fields=[
                ('GP_id', models.AutoField(primary_key=True, serialize=False)),
                ('GP_heading', models.CharField(max_length=20)),
                ('GP_plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gold_Plan_Price',
            fields=[
                ('GPP_id', models.AutoField(primary_key=True, serialize=False)),
                ('GPP_name', models.CharField(max_length=20)),
                ('GPP_Price', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Platinum_Plan',
            fields=[
                ('PP_id', models.AutoField(primary_key=True, serialize=False)),
                ('PP_heading', models.CharField(max_length=20)),
                ('PP_plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platinum_Plan_Price',
            fields=[
                ('PPP_id', models.AutoField(primary_key=True, serialize=False)),
                ('PPP_name', models.CharField(max_length=20)),
                ('PPP_Price', models.IntegerField(default='')),
            ],
        ),
    ]
