# Generated by Django 3.0.7 on 2020-07-06 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0004_gold_plan_gold_plan_price_platinum_plan_platinum_plan_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gold_Plan_Price',
        ),
        migrations.DeleteModel(
            name='Platinum_Plan_Price',
        ),
    ]
