# Generated by Django 3.0.7 on 2020-07-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0005_auto_20200707_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=100)),
                ('tdesc', models.CharField(max_length=300)),
                ('trole', models.CharField(max_length=50)),
                ('timg', models.ImageField(upload_to='Evento/images')),
            ],
        ),
    ]
