# Generated by Django 3.0.7 on 2020-07-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0007_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='state',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='zipc',
        ),
    ]
