# Generated by Django 3.0.7 on 2020-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0008_auto_20200707_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsImage',
            fields=[
                ('EI_id', models.AutoField(primary_key=True, serialize=False)),
                ('EI_heading', models.CharField(max_length=100)),
                ('EI_loc', models.CharField(max_length=50)),
                ('EI_category', models.CharField(max_length=100)),
                ('EI_img', models.ImageField(upload_to='Evento/images')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
