# Generated by Django 3.0.7 on 2020-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0010_eventstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
    ]
