# Generated by Django 3.0.7 on 2020-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0012_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='slide_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='tdesc',
            field=models.TextField(),
        ),
    ]
